# 🐍 1. Numpy Basics
### 🎓 **Advanced Machine Learning 2024**
#### 👨‍🏫 **By: George Samuel**

---

## 💡 What is Numpy?

### 📌 Core Definition
**Numpy** is one of the primarily used data structures to **represent & process data**.

### 🏗️ The Structure
It is about creating **N-dimensional Tensors**.
* These Tensors are technically called: **Numpy Arrays** or `ndarray`.

---

## 🔢 Array Dimensions
Numpy arrays come in different shapes:

* **⏺️ 0-Dimensional** $\rightarrow$ **(Scalars)**
* **➖ 1-Dimensional** $\rightarrow$ **(Vectors)**
* **▦ 2-Dimensional** $\rightarrow$ **(Matrices)**
* **🖼️ 3-Dimensional** $\rightarrow$ **(Images)**

In [1]:
import numpy as np

In [5]:
mat=np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(mat)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## **Create Numpy Arrays:**

In [77]:
# create scalers(0-d array)
s=np.array(5)
print(s)
# create 1-d array= vector
v=np.array([1,2,3])
print(v)
# create 2-d array= matrix
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(m)

5
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**shape:**

In [78]:
# reshape
r=m.reshape(1,9)
print(r)
r2=m.reshape(9,1)
print(r2)

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**Add Dimension**

In [79]:
# 1-By using reshape method
vec=np.array([1,2,3,4])
mat=vec.reshape((vec.shape[0],1))
print(mat)
# -----
# 2-By using none
vec=np.array([1,2,3,4])
mat=vec[:,None]
print(mat)

[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]


In [80]:
from p import reshape_vector_to_matrix
reshape_vector_to_matrix(np.array([1,2,3,4,5,6]))


array([[1, 2, 3],
       [4, 5, 6]])

**Dtype:**
*  Numpy array can only carry one data type.
*  If you pass elements with different datatypes, Numpy will 
change all of them into one datatype (the most general 
dtype).
*  Here is the order of general datatypes:
*  Object > String > Float > Int > Bool

In [81]:
# Dtype examples
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]]
)
print(mat.dtype)  # default dtype is int
# float dtype
mat=np.array([[.1,2,3],
              [4,5,6],
              [7,8,9]]
)
print(mat.dtype)  
# int dtype
mat=np.array([[1,2,3],
              [True,5,6],
              [7,8,9]]
)
print(mat.dtype)  
# string dtype
mat=np.array([[1,2,3],
              [4,"5",6],
              [7,8,9]]
)
print(mat.dtype) 
# object dtype
class C:
    x=3
o1=C()
mat=np.array([[o1,1],
                  [2,3]])
print(mat.dtype)

int64
float64
int64
<U21
object


**Change Dtype**

In [82]:
mat=np.array([[1,2,3],
              [4,"5",6],
              [7,8,9]]
, dtype=str)
print(mat.dtype)
print(mat)

<U1
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


**Indexing**

In [83]:
v=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
v[1]
v[1,2]
v[-2]
v[:,1] #vertical slice
v[1,:] #horizontal slice
v[0:2,0:2] #sub matrix 
v[::2,::2] #sub matrix with step 2
v[v>5]  #conditional selection 
v[(v>2) & (v<8)]  #conditional selection
v[1,-2]

np.int64(5)

**Transopose**:Make matrix columns become rows and rows become 
columns.

In [84]:
mat=np.array([[1,2,3],
              [4,5,6],
                [7,8,9]])
mat_t=mat.T
print(mat_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


<!-- **Quick Array Creation**
* Numpy provides you some built-in methods that helps you 
create arrays quickly
* In the coming slides, you will find the most popular 
methods. -->


In [85]:
# Zeros matrix
z=np.zeros((3,4))
z
# ones()
o=np.ones((2,3))
o
# Full()
f=np.full((2,3),7)
f
# Empty()
e=np.empty((2,3))
e
# arange()
a=np.arange(10)
a
a2=np.arange(2,10,2)
a2
# Linspace()
l=np.linspace(0,10,num=25)
mat=l.reshape(5,5)
# print(f" l=\n{l}\n mat=\n{mat}")
# Identity ():
I=np.identity(4,dtype=int)
I
# Random.random(): between 0 and 1
r=np.random.random((3,3))
r
# Random.randint(): between low and high
ri=np.random.randint(1,10,(3,3))
# riRandom.choice():
rc=np.random.choice([10,20,30,40,50],(3,3))
rc


array([[20, 40, 10],
       [20, 40, 30],
       [40, 30, 30]])

**NPZ files**
* Numpy provides a way to save your numpy arrays as files
called npz files which helps you to save the data you want
in npz format.
* You can save the files using a built-in method called savez,
and you can load using a built-in method called load.


In [86]:
# to save
np.savez('file.npz',mat_1=mat,rerandom=rc)
# to load
with np.load('file.npz') as file:
    mat=file['mat_1']
    rc=file['rerandom']

**Stacking**

In [87]:
# Stacking arrays
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
# Vertical stacking
v=np.vstack((a,b))
v
# Horizontal stacking
h=np.hstack((a,b))
h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**Comparison**
* Is about elementwise comparison between two numpy arrays.
* The result is a Boolean numpy array with the same shape.


In [88]:
# Examples
# compare an array with a scalar
s=4
v=np.array([1,2,3,4])
v==s
# compare two arrays
a1=np.array([1,2,3,4])
a2=np.array([4,3,2,1])
a1==a2
# compare two matrices
m1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
m2=np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
m1==m2
# comparison using all()
m1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
np.all(m1>=1)
# comparison using any()
m1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
np.any(m1>8)
# comparison using isclose()
a1=np.array([1.0,2.0,3.0])
a2=np.array([0.9999,2.0001,3.0])
np.isclose(a1,a2,atol=1) #atol=1 means absolute tolerance
# Comparison using allclose():
a1=np.array([1.0,2.0,3.0])
a2=np.array([0.9999,2.0001,3.0])
np.allclose(a1,a2,atol=1) #atol=1 means absolute tolerance

True

**Conditional Access**
* It means getting elements of an array that satisfy a specific 
condition.
* A Condition means the result of elementwise comparison, we 
saw in the previous section.

In [89]:
v=np.array([1,2,3,4,5])
condions=v>3
print(condions)
condional_access=v[condions]
print(condional_access)

[False False False  True  True]
[4 5]


In [90]:
# conditional by using modification
# using '=='
v=np.array([1,2,3,4,5])
condion=v>=4
v[condion]=-1
print(v)
# using where()
v=np.array([1,2,3,4,5])
condion=v>=4
v=np.where(condion,-1,v)
print(v)


[ 1  2  3 -1 -1]
[ 1  2  3 -1 -1]


**Array BroadCasting**


In [95]:
# Vector/Scalar BroadCasting
v1=np.array([1,2,3])
c=2
summation=v1+c
multiplication=v1*c
print(summation)
print("-----")
print(multiplication)
print("-----")
#  Matrix/Vector BroadCasting
mat1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
v=np.array([1,0,1])
summation=mat1+v
multiplication=mat1*v
print(summation)
print("-----")
print(multiplication)

[3 4 5]
-----
[2 4 6]
-----
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
-----
[[1 0 3]
 [4 0 6]
 [7 0 9]]


**Sparse Matrices**
* Sparse matrix is a matrix that contain mostly zero values.
* The opposite of sparse matrix is **dense matrix**, which is a 
matrix where most of the values are non-zero.
* Sparse matrices has a problem related to waste of memory 
resources as those zero values do not contain any 
information.
Numpy
Advanced Machine Learning 2024 by George Samuel
Sparse Matrix:
* The solution is to transform it into another data structure. 
Where the zero values can be ignored.


In [98]:
# we have to techniques to avoid modifying the original array while doing operations that change the array. These techniques are:
# Dense Matrix to CSR matrix
from scipy.sparse import csr_matrix,csc_matrix
dense_mat=np.array([[0,0,3],
                    [4,0,0],
                    [0,0,9]])
sparse_mat=csr_matrix(dense_mat)
print(sparse_mat)
print("-----")
# Dense Matrix to CSC matrix
sparse_mat_csc=csc_matrix(dense_mat)
print(sparse_mat_csc)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (1, 0)	4
  (2, 2)	9
-----
<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (1, 0)	4
  (0, 2)	3
  (2, 2)	9
