# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [2]:
import sys

# 1. بنحدد مسار الفولدر (بدون اسم الملف p.py)
# استخدمنا r قبل علامة التنصيص عشان الـ Backslashes متعملش مشاكل
folder_path = r'D:\ai_deploma_master\ai_deploma_master\code'

# 2. بنضيف الفولدر لقائمة المسارات اللي بايثون بيشوفها

sys.path.append(folder_path)

# 3. دلوقتي بنعمل Import من ملف p
from p import array_factory

array_factory("one",(3,3))



'please enter the correct mode'

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [8]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        # arr = np.array(data1)

        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape 
        # Common usage: turning a vector (1D) into a matrix (2D)  by using reshape function 
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical Stacking (vstack) 
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return  arr1, arr2,reshaped_arr1,combined_dataset


    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")
data_1 = [1, 2, 3, 4, 5, 6]
data_2 = [[7, 8, 9], [10, 11, 12]]
shape = (2, 3)    
secure_reshape_and_stack(data_1,data_2,shape)

res1, res2, reshaped, combine = secure_reshape_and_stack(data_1, data_2, shape)
print(combine)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [18]:
import numpy as np


def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. تحويل المدخلات إلى مصفوفة NumPy
    arr = np.array(arr)
    
    # 2. تحديد الشرط
    # هنا مش بنستخدم if لأن NumPy بتقارن كل عنصر لوحده (Element-wise)
    condition = (arr >= threshold)
    
    # 3. تطبيق التعديل باستخدام np.where
    # المنطق: (لو الشرط صح حط القيمة الجديدة، لو غلط سيب القيمة الأصلية)
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

# تجربة الكود
arr = [10, 20, 3, 40, 50, 8, 105]
threshold = 20
replacement_value = -1

result = apply_threshold(arr, threshold, replacement_value)
print(result)
# الناتج المتوقع: [ 10 -1  3 -1 -1  8 -1]

[10 -1  3 -1 -1  8 -1]


TestCase

In [20]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = 3
replacement_value = -1
# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b,replacement_value)
print(final_report)
# Resulting shape: (4, 3)

[ 1  2 -1 -1 -1 -1]


In [15]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])